### ISSUE TITLE
Support Rolling Update

### ISSUE THREAD

**Issue by a-r-g-v** [a-r-g-v/nata#8]
backendServices().getHealth() を見ながら，100%を維持しながら古いインスタンスを消していく．

**Comment by a-r-g-v** [comment]
```
======================================================================
ERROR: test_drivers (tests.test_drivers.DriversTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/debian/nata/tests/test_drivers.py", line 72, in test_drivers
    app_resorces.rolling(lb)
  File "/home/debian/nata/nata/resources.py", line 150, in rolling
    desire_stable_count = self.count_stable_instances(lb)
  File "/home/debian/nata/nata/resources.py", line 133, in count_stable_instances
    raise Exception
Exception

----------------------------------------------------------------------
```
